# Generated by Django 5.1.4 on 2026-07-04 20:14

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='ciudadano_rut',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=12)),
        ),
    ]
