global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # ─── PROMETHEUS SE MONITOREA A SÍ MISMO ──────────────────────────────────
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ─── NGINX ────────────────────────────────────────────────────────────────
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-gateway:80']
    metrics_path: /health

  # ─── SERVICIOS DJANGO ─────────────────────────────────────────────────────
  - job_name: 'servicio-auth'
    static_configs:
      - targets: ['servicio-auth:8000']
    metrics_path: /api/auth/verificar/

  - job_name: 'servicio-tramites'
    static_configs:
      - targets: ['servicio-tramites:8000']
    metrics_path: /tramites/tipos/

  - job_name: 'servicio-bodega'
    static_configs:
      - targets: ['servicio-bodega:8000']
    metrics_path: /bodega/categorias/